version: '3.8'

services:
  db:
    image: supabase/postgres:15.1.0.89
    ports:
      - "54322:5432"
    environment:
      POSTGRES_PASSWORD: your-super-secret-password
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./supabase/migrations:/docker-entrypoint-initdb.d/migrations
      - ./supabase/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  studio:
    image: supabase/studio:latest
    ports:
      - "3000:3000"
    environment:
      STUDIO_PG_META_URL: http://meta:8080
      POSTGRES_PASSWORD: your-super-secret-password
    depends_on:
      - meta
      - db

  kong:
    image: kong:2.8.1
    ports:
      - "8000:8000"
      - "8443:8443"
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/var/lib/kong/kong.yml"
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_PLUGINS: "request-transformer,cors,key-auth,acl"
    volumes:
      - ./supabase/kong.yml:/var/lib/kong/kong.yml
    depends_on:
      - db

  auth:
    image: supabase/gotrue:v2.120.3
    environment:
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://postgres:your-super-secret-password@db:5432/postgres?sslmode=disable
      GOTRUE_SITE_URL: http://localhost:3000
      GOTRUE_URI_ALLOW_LIST: http://localhost:3000,http://localhost:3001,http://localhost:3002
      GOTRUE_DISABLE_SIGNUP: "false"
      GOTRUE_JWT_SECRET: your-super-secret-jwt-token
      GOTRUE_JWT_EXP: 3600
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_DB_MAX_RETRIES: 10
    depends_on:
      db:
        condition: service_healthy

  rest:
    image: postgrest/postgrest:v11.2.0
    ports:
      - "3001:3000"
    environment:
      PGRST_DB_URI: postgres://postgres:your-super-secret-password@db:5432/postgres
      PGRST_DB_SCHEMA: public,storage,graphql_public
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: your-super-secret-jwt-token
      PGRST_DB_USE_LEGACY_GUCS: "false"
    depends_on:
      - db

  storage:
    image: supabase/storage-api:v0.40.6
    environment:
      DATABASE_URL: postgres://postgres:your-super-secret-password@db:5432/postgres
      PGRST_JWT_SECRET: your-super-secret-jwt-token
      FILE_SIZE_LIMIT: 52428800
      STORAGE_BACKEND: file
      FILE_STORAGE_BACKEND_PATH: /var/lib/storage
    volumes:
      - ./storage:/var/lib/storage
    depends_on:
      - db

  meta:
    image: supabase/postgres-meta:v0.66.2
    environment:
      PG_META_PORT: 8080
      PG_META_DB_HOST: db
      PG_META_DB_PASSWORD: your-super-secret-password
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db-data:
